kind: Service
apiVersion: v1
metadata:
  name:  nodejs-alpine-service
spec:
  type:  NodePort
  selector:
    app: nodejs-alpine
  ports:
  - protocol: TCP
    port: 85
    nodePort: 32505

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-alpine-deployment
  labels:
    app: nodejs-alpine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-alpine
  template:
    metadata:
      labels:
        app: nodejs-alpine
    spec:
      containers:
      - name: nodejs-alpine
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 85
